#!/usr/bin/env bash
# Installs nginx, configures index.html, 404 error and 301 redirect
# Also inserts custom header in /etc/nginx/sites-available/default

apt-get update -y
apt-get install -y nginx

mkdir -p /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
touch /etc/nginx/html/404-error.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404-error.html

printf %s "server {
        listen  80;
        listen [::]:80 default_server;
        add_header X-Served-By $HOSTNAME;
        root    /etc/nginx/html;
        index   index.html index.htm;

        location /redirect_me {
                return 301 http://google.com/;
        }

        error_page 404 /404-error.html;
        location /404 {
                root /etc/nginx/html;
                internal;
        }
}" > /etc/nginx/sites-available/default

service nginx restart
