#!/usr/bin/env bash
# Installs HAproxy 2.0, uses roundrobin algorithm, managed via init script

apt-get sudo  install software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-2.0 -y
apt-get update -y
apt-get install haproxy=2.0.\* -y
# Copies default config just in case :)
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig

echo "ENABLED=1" >> /etc/default/haproxy
sudo sed -i "$ a $frontend_setup" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a $backend_setup" /etc/haproxy/haproxy.cfg

sudo service haproxy restart
