#!/usr/bin/env bash
#sudo sed -ri "s/[0-9]*?\sdefault_server/80 default_server/g" /etc/nginx/sites-available/default
#sudo sed -ri "s/[0-9]*?\sdefault_server/80 default_server/g" /etc/nginx/sites-enabled/default
sudo sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
sudo service nginx restart
